# Generated by Django 4.2.27 on 2025-12-24 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(choices=[('YELLOW', 'Yellow'), ('BLUE', 'Blue'), ('BLACK', 'Black')], max_length=20, unique=True)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('x_coordinate', models.FloatField(default=0.0)),
                ('y_coordinate', models.FloatField(default=0.0)),
                ('default_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('status', models.CharField(choices=[('NEUTRAL', 'Neutral'), ('CAPTURING', 'Capturing'), ('OWNED', 'Owned'), ('CONTESTED', 'Contested')], default='NEUTRAL', max_length=20)),
                ('capture_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_score_update', models.DateTimeField(blank=True, null=True)),
                ('capturing_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capturing_zones', to='game.team')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_zones', to='game.team')),
            ],
        ),
    ]
