# Generated by Django 4.2.27 on 2025-12-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='is_base',
            field=models.BooleanField(default=False),
        ),
    ]
