# Generated by Django 4.2.27 on 2025-12-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_zone_is_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='adjacent_zones',
            field=models.ManyToManyField(blank=True, to='game.zone'),
        ),
    ]
