# Generated by Django 4.2.27 on 2025-12-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_zone_adjacent_zones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
