# Generated by Django 4.2.30 on 2026-04-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_repair_legacy_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
