# Generated by Django 4.2.30 on 2026-04-23 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_rebuild_zone_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('STANDARD', 'Standard'), ('FREE', 'Free'), ('QR', 'QR')], default='STANDARD', max_length=8),
        ),
    ]
